#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AiciAndroid.Resource", IsApplication=true)]

namespace AiciAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_btn_speak_now = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_call = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_help = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_preferences = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_refresh = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sym_action_email = 2130837510;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060019
			public const int Apptitle = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int BrainPref = 2131099670;
			
			// aapt resource value: 0x7f06000b
			public const int BtnAddCalOk = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int BtnAddCalSpeak = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int CalendarData = 2131099648;
			
			// aapt resource value: 0x7f060017
			public const int FontPref = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int ImgBackground = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int Input = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int LangPref = 2131099672;
			
			// aapt resource value: 0x7f060003
			public const int LblDate = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int LblDateData = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int LblDescription = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int LblDescriptionData = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int LblEndDate = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int LblEndDateData = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int LblLocation = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int LblLocationData = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int LblTitle = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int LblTitleData = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int Log_List_Item = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int MainLayout = 2131099665;
			
			// aapt resource value: 0x7f06001c
			public const int Menu_Info = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int Menu_Preferences = 2131099677;
			
			// aapt resource value: 0x7f06001b
			public const int Menu_SyncContacts = 2131099675;
			
			// aapt resource value: 0x7f060012
			public const int Mic = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int SelectedColor = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int SelectedImage = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int Send = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int ToggleIsRunning = 2131099674;
			
			// aapt resource value: 0x7f06000f
			public const int homepage = 2131099663;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddCalendarItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ColorPickerPref = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ImagePickerPref = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Info = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Log_List_Item = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MainList = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int prefs = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TitleBar = 2130903047;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainMenu = 2131034112;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001b
			public const int AddCalExtra = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int AddCalOk = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int AddCalSpeak = 2130968605;
			
			// aapt resource value: 0x7f040019
			public const int AddCalUntil = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int AddCalWhat = 2130968602;
			
			// aapt resource value: 0x7f040018
			public const int AddCalWhen = 2130968600;
			
			// aapt resource value: 0x7f040017
			public const int AddCalWhere = 2130968599;
			
			// aapt resource value: 0x7f040014
			public const int ApplicationName = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int BrainPrefKey = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int BrainPrefSummary = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int BrainPrefTitle = 2130968577;
			
			// aapt resource value: 0x7f040020
			public const int Info_About_Title = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int Info_By_Title = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int Info_Chatting_Title = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int Info_availableCommands_Title = 2130968606;
			
			// aapt resource value: 0x7f040011
			public const int InitStackSizePrefKey = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int InitStackSizePrefSummary = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int InitStackSizePrefTitle = 2130968594;
			
			// aapt resource value: 0x7f040008
			public const int InputVarCountPrefKey = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int InputVarCountPrefSummary = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int InputVarCountPrefTitle = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int LanguagePrefKey = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int LanguagePrefSummary = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int LanguagePrefTitle = 2130968580;
			
			// aapt resource value: 0x7f04000e
			public const int MaxConcurrentProcPrefKey = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int MaxConcurrentProcPrefSummary = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int MaxConcurrentProcPrefTitle = 2130968591;
			
			// aapt resource value: 0x7f040015
			public const int MenuPanicTitle = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int MenuPrefTitle = 2130968598;
			
			// aapt resource value: 0x7f04000b
			public const int MinReservedBlockedProcPrefKey = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int MinReservedBlockedProcPrefSummary = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int MinReservedBlockedProcPrefTitle = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int SpeedOptPrefSummary = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int SpeedOptPrefTitle = 2130968582;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
