//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaStDev.HAB.Designer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JaStDev.HAB.Designer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APP_REF_FORMAT.
        /// </summary>
        internal static string APPREFFORMAT {
            get {
                return ResourceManager.GetString("APPREFFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSETCOLUMN.
        /// </summary>
        internal static string ASSETCOLUMN {
            get {
                return ResourceManager.GetString("ASSETCOLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset files (*.asset.xml)|*.asset.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string AssetFileFilter {
            get {
                return ResourceManager.GetString("AssetFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSETRECORDFORMAT.
        /// </summary>
        internal static string ASSETRECORDFORMAT {
            get {
                return ResourceManager.GetString("ASSETRECORDFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachedTopics.bin.
        /// </summary>
        internal static string AttachedTopicsFileName {
            get {
                return ResourceManager.GetString("AttachedTopicsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chatlog files (*.xcl)|*.xcl|All files (*.*)|*.*.
        /// </summary>
        internal static string ChatLogFileFilter {
            get {
                return ResourceManager.GetString("ChatLogFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODEITEMFORMAT.
        /// </summary>
        internal static string CodeItemFormat {
            get {
                return ResourceManager.GetString("CodeItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITIONPATTERNFORMAT.
        /// </summary>
        internal static string CONDITIONPATTERNFORMAT {
            get {
                return ResourceManager.GetString("CONDITIONPATTERNFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv files (*.csv)|*.csv|All files (*.*)|*.*.
        /// </summary>
        internal static string CSVFileFilter {
            get {
                return ResourceManager.GetString("CSVFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomDict.lex.
        /// </summary>
        internal static string CustomSpellingDict {
            get {
                return ResourceManager.GetString("CustomSpellingDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUTOPERATION.
        /// </summary>
        internal static string CUTOPERATION {
            get {
                return ResourceManager.GetString("CUTOPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelayLoadFormat.
        /// </summary>
        internal static string DelayLoadFormat {
            get {
                return ResourceManager.GetString("DelayLoadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelayLoadResultType.
        /// </summary>
        internal static string DelayLoadResultType {
            get {
                return ResourceManager.GetString("DelayLoadResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOPATTERNFORMAT.
        /// </summary>
        internal static string DOPATTERNFORMAT {
            get {
                return ResourceManager.GetString("DOPATTERNFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditorOverviewFORMAT.
        /// </summary>
        internal static string EDITORFORMAT {
            get {
                return ResourceManager.GetString("EDITORFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FERESTRICTIONFORMAT.
        /// </summary>
        internal static string FERestrictionFormat {
            get {
                return ResourceManager.GetString("FERestrictionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLOWEDITORFORMAT.
        /// </summary>
        internal static string FLOWEDITORFORMAT {
            get {
                return ResourceManager.GetString("FLOWEDITORFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLOWITEMFORMAT.
        /// </summary>
        internal static string FLOWITEMFORMAT {
            get {
                return ResourceManager.GetString("FLOWITEMFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMEELEMENTFORMAT.
        /// </summary>
        internal static string FrameElementFormat {
            get {
                return ResourceManager.GetString("FrameElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMEEVOKERFORMAT.
        /// </summary>
        internal static string FrameEvokerFormat {
            get {
                return ResourceManager.GetString("FrameEvokerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMEFORMAT.
        /// </summary>
        internal static string FRAMEFORMAT {
            get {
                return ResourceManager.GetString("FRAMEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMEORIGINFORMAT.
        /// </summary>
        internal static string FrameOriginFormat {
            get {
                return ResourceManager.GetString("FrameOriginFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAMESEQUENCEFORMAT.
        /// </summary>
        internal static string FrameSequenceFormat {
            get {
                return ResourceManager.GetString("FrameSequenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global pattern files (*.global.xml)|*.global.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string globalsFileFilter {
            get {
                return ResourceManager.GetString("globalsFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IgnoreAllDict.lex.
        /// </summary>
        internal static string IgnoreAllDict {
            get {
                return ResourceManager.GetString("IgnoreAllDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic files (*.topic.xml)|*.topic.xml|AIML files (*.aiml)|*.aiml|All files (*.*)|*.*.
        /// </summary>
        internal static string ImportTopicFileFilter {
            get {
                return ResourceManager.GetString("ImportTopicFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALIDPATTERNFORMAT.
        /// </summary>
        internal static string INVALIDPATTERNFORMAT {
            get {
                return ResourceManager.GetString("INVALIDPATTERNFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsThesRelRecursiveFormat.
        /// </summary>
        internal static string IsThesRelRecursiveFormat {
            get {
                return ResourceManager.GetString("IsThesRelRecursiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINDMAPITEM.
        /// </summary>
        internal static string MindMapItemFormat {
            get {
                return ResourceManager.GetString("MindMapItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MindMapLinkSide.
        /// </summary>
        internal static string MindMapLinkSide {
            get {
                return ResourceManager.GetString("MindMapLinkSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIXEDTEXTPATTERNFORMAT.
        /// </summary>
        internal static string MIXEDTEXTPATTERNFORMAT {
            get {
                return ResourceManager.GetString("MIXEDTEXTPATTERNFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module files (*.nnm)|*.nnm|All files (*.*)|*.*.
        /// </summary>
        internal static string ModuleFileFilter {
            get {
                return ResourceManager.GetString("ModuleFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MULTIASSETRECORDFORMAT.
        /// </summary>
        internal static string MULTIASSETRECORDFORMAT {
            get {
                return ResourceManager.GetString("MULTIASSETRECORDFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiMindMapItemFormat.
        /// </summary>
        internal static string MultiMindMapItemFormat {
            get {
                return ResourceManager.GetString("MultiMindMapItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiNeuronIDFormat.
        /// </summary>
        internal static string MultiNeuronIDFormat {
            get {
                return ResourceManager.GetString("MultiNeuronIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiUIElementFormat.
        /// </summary>
        internal static string MultiUIElementFormat {
            get {
                return ResourceManager.GetString("MultiUIElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NeuronIDFormat.
        /// </summary>
        internal static string NeuronIDFormat {
            get {
                return ResourceManager.GetString("NeuronIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neural network files (*.nnl)|*.nnl|All files (*.*)|*.*.
        /// </summary>
        internal static string NNLFileFilter {
            get {
                return ResourceManager.GetString("NNLFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Tree item selected in the project overview to put new items in..
        /// </summary>
        internal static string NoProjectTreeItemSelected {
            get {
                return ResourceManager.GetString("NoProjectTreeItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUTPATTERNFORMAT.
        /// </summary>
        internal static string OUTPUTPATTERNFORMAT {
            get {
                return ResourceManager.GetString("OUTPUTPATTERNFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patterns for .
        /// </summary>
        internal static string PatternsForText {
            get {
                return ResourceManager.GetString("PatternsForText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries (*.xnq)|*.xnq|All files (*.*)|*.*.
        /// </summary>
        internal static string QueryFileFilter {
            get {
                return ResourceManager.GetString("QueryFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source files (*.nnl)|*.nnl|All files (*.*)|*.*.
        /// </summary>
        internal static string SourceFilesFilter {
            get {
                return ResourceManager.GetString("SourceFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXTPATTERNDEFFORMAT.
        /// </summary>
        internal static string TEXTPATTERNDEFFORMAT {
            get {
                return ResourceManager.GetString("TEXTPATTERNDEFFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXTPATTERNFORMAT.
        /// </summary>
        internal static string TEXTPATTERNFORMAT {
            get {
                return ResourceManager.GetString("TEXTPATTERNFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thesaurus files (*.thesaurus.xml)|*.thesaurus.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string ThesaurusFileFilter {
            get {
                return ResourceManager.GetString("ThesaurusFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThesaurusRelationshipFormat.
        /// </summary>
        internal static string ThesaurusRelationshipFormat {
            get {
                return ResourceManager.GetString("ThesaurusRelationshipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thesaurus section files (*.section.xml)|*.section.xml|.
        /// </summary>
        internal static string ThesaurusSectionFileFilter {
            get {
                return ResourceManager.GetString("ThesaurusSectionFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolboxItemFormat.
        /// </summary>
        internal static string ToolboxItemFormat {
            get {
                return ResourceManager.GetString("ToolboxItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic files (*.topic.xml)|*.topic.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string TopicFileFilter {
            get {
                return ResourceManager.GetString("TopicFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UIElement.
        /// </summary>
        internal static string UIElementFormat {
            get {
                return ResourceManager.GetString("UIElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISUALFRAMEFORMAT.
        /// </summary>
        internal static string VISUALFRAMEFORMAT {
            get {
                return ResourceManager.GetString("VISUALFRAMEFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://bragisoft.com.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORDNETDRAGFORMAT.
        /// </summary>
        internal static string WORDNETDRAGFORMAT {
            get {
                return ResourceManager.GetString("WORDNETDRAGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML.
        /// </summary>
        internal static string XamlFormat {
            get {
                return ResourceManager.GetString("XamlFormat", resourceCulture);
            }
        }
    }
}
