//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaStDev.HAB.Designer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTemplatePath {
            get {
                return ((string)(this["DefaultTemplatePath"]));
            }
            set {
                this["DefaultTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0000FF")]
        public global::System.Windows.Media.SolidColorBrush DialogTextOutColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["DialogTextOutColor"]));
            }
            set {
                this["DialogTextOutColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSave {
            get {
                return ((bool)(this["AutoSave"]));
            }
            set {
                this["AutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:10:00")]
        public global::System.TimeSpan AutoSaveInterval {
            get {
                return ((global::System.TimeSpan)(this["AutoSaveInterval"]));
            }
            set {
                this["AutoSaveInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoAddItemsToMindMapCluter {
            get {
                return ((bool)(this["AutoAddItemsToMindMapCluter"]));
            }
            set {
                this["AutoAddItemsToMindMapCluter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("460")]
        public double ApplicationHeight {
            get {
                return ((double)(this["ApplicationHeight"]));
            }
            set {
                this["ApplicationHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public double ApplicationWidth {
            get {
                return ((double)(this["ApplicationWidth"]));
            }
            set {
                this["ApplicationWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ApplicationTop {
            get {
                return ((double)(this["ApplicationTop"]));
            }
            set {
                this["ApplicationTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ApplicationLeft {
            get {
                return ((double)(this["ApplicationLeft"]));
            }
            set {
                this["ApplicationLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState ApplicationWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["ApplicationWindowState"]));
            }
            set {
                this["ApplicationWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.SolidColorBrush DialogTextInColor {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["DialogTextInColor"]));
            }
            set {
                this["DialogTextInColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastOpened {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastOpened"]));
            }
            set {
                this["LastOpened"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SandboxPath {
            get {
                return ((string)(this["SandboxPath"]));
            }
            set {
                this["SandboxPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FrameNetPath {
            get {
                return ((string)(this["FrameNetPath"]));
            }
            set {
                this["FrameNetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedEditorsOverview {
            get {
                return ((bool)(this["ToolbarExpandedEditorsOverview"]));
            }
            set {
                this["ToolbarExpandedEditorsOverview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedDescriptionView {
            get {
                return ((bool)(this["ToolbarExpandedDescriptionView"]));
            }
            set {
                this["ToolbarExpandedDescriptionView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedDebugger {
            get {
                return ((bool)(this["ToolbarExpandedDebugger"]));
            }
            set {
                this["ToolbarExpandedDebugger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedNeuronExplorer {
            get {
                return ((bool)(this["ToolbarExpandedNeuronExplorer"]));
            }
            set {
                this["ToolbarExpandedNeuronExplorer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedThesaurusView {
            get {
                return ((bool)(this["ToolbarExpandedThesaurusView"]));
            }
            set {
                this["ToolbarExpandedThesaurusView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedTimersView {
            get {
                return ((bool)(this["ToolbarExpandedTimersView"]));
            }
            set {
                this["ToolbarExpandedTimersView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedWordNetChannel {
            get {
                return ((bool)(this["ToolbarExpandedWordNetChannel"]));
            }
            set {
                this["ToolbarExpandedWordNetChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedAudioChannel {
            get {
                return ((bool)(this["ToolbarExpandedAudioChannel"]));
            }
            set {
                this["ToolbarExpandedAudioChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedFlowEditor {
            get {
                return ((bool)(this["ToolbarExpandedFlowEditor"]));
            }
            set {
                this["ToolbarExpandedFlowEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FlowItemDisplayMode {
            get {
                return ((int)(this["FlowItemDisplayMode"]));
            }
            set {
                this["FlowItemDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolboxExpandedNeuronExplorer {
            get {
                return ((bool)(this["ToolboxExpandedNeuronExplorer"]));
            }
            set {
                this["ToolboxExpandedNeuronExplorer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedCodeEditor {
            get {
                return ((bool)(this["ToolbarExpandedCodeEditor"]));
            }
            set {
                this["ToolbarExpandedCodeEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int MaxConcurrentProcessors {
            get {
                return ((int)(this["MaxConcurrentProcessors"]));
            }
            set {
                this["MaxConcurrentProcessors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int InitProcessorStackSize {
            get {
                return ((int)(this["InitProcessorStackSize"]));
            }
            set {
                this["InitProcessorStackSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VerbNetPath {
            get {
                return ((string)(this["VerbNetPath"]));
            }
            set {
                this["VerbNetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegExFile {
            get {
                return ((string)(this["RegExFile"]));
            }
            set {
                this["RegExFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedFrameEditor {
            get {
                return ((bool)(this["ToolbarExpandedFrameEditor"]));
            }
            set {
                this["ToolbarExpandedFrameEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double NDBBrowserWidth {
            get {
                return ((double)(this["NDBBrowserWidth"]));
            }
            set {
                this["NDBBrowserWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double NDBBrowserHeight {
            get {
                return ((double)(this["NDBBrowserHeight"]));
            }
            set {
                this["NDBBrowserHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedTextChannelView {
            get {
                return ((bool)(this["ToolbarExpandedTextChannelView"]));
            }
            set {
                this["ToolbarExpandedTextChannelView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedReflectionChannel {
            get {
                return ((bool)(this["ToolbarExpandedReflectionChannel"]));
            }
            set {
                this["ToolbarExpandedReflectionChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedMemProfiler {
            get {
                return ((bool)(this["ToolbarExpandedMemProfiler"]));
            }
            set {
                this["ToolbarExpandedMemProfiler"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedAssetEditor {
            get {
                return ((bool)(this["ToolbarExpandedAssetEditor"]));
            }
            set {
                this["ToolbarExpandedAssetEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedTestCases {
            get {
                return ((bool)(this["ToolbarExpandedTestCases"]));
            }
            set {
                this["ToolbarExpandedTestCases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedVisualEditor {
            get {
                return ((bool)(this["ToolbarExpandedVisualEditor"]));
            }
            set {
                this["ToolbarExpandedVisualEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedImageChannelView {
            get {
                return ((bool)(this["ToolbarExpandedImageChannelView"]));
            }
            set {
                this["ToolbarExpandedImageChannelView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CharactersPath {
            get {
                return ((string)(this["CharactersPath"]));
            }
            set {
                this["CharactersPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CharacterExtractionPath {
            get {
                return ((string)(this["CharacterExtractionPath"]));
            }
            set {
                this["CharacterExtractionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedChatBotView {
            get {
                return ((bool)(this["ToolbarExpandedChatBotView"]));
            }
            set {
                this["ToolbarExpandedChatBotView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string SettingsVersion {
            get {
                return ((string)(this["SettingsVersion"]));
            }
            set {
                this["SettingsVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DesignerTriggersNetworkEvents {
            get {
                return ((bool)(this["DesignerTriggersNetworkEvents"]));
            }
            set {
                this["DesignerTriggersNetworkEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditorsUseSpellcheck {
            get {
                return ((bool)(this["EditorsUseSpellcheck"]));
            }
            set {
                this["EditorsUseSpellcheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int MaxNrOfUndo {
            get {
                return ((int)(this["MaxNrOfUndo"]));
            }
            set {
                this["MaxNrOfUndo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consolas")]
        public global::System.Windows.Media.FontFamily PatternEditorsFont {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["PatternEditorsFont"]));
            }
            set {
                this["PatternEditorsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextPatternSearchMatchCase {
            get {
                return ((bool)(this["TextPatternSearchMatchCase"]));
            }
            set {
                this["TextPatternSearchMatchCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextPatternSearchIncludeNoReply {
            get {
                return ((bool)(this["TextPatternSearchIncludeNoReply"]));
            }
            set {
                this["TextPatternSearchIncludeNoReply"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TextPatternSearchScope {
            get {
                return ((int)(this["TextPatternSearchScope"]));
            }
            set {
                this["TextPatternSearchScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextPatternSearchAsRegEx {
            get {
                return ((bool)(this["TextPatternSearchAsRegEx"]));
            }
            set {
                this["TextPatternSearchAsRegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextPatternSearchIncludeOutput {
            get {
                return ((bool)(this["TextPatternSearchIncludeOutput"]));
            }
            set {
                this["TextPatternSearchIncludeOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextPatternSearchIncludeinput {
            get {
                return ((bool)(this["TextPatternSearchIncludeinput"]));
            }
            set {
                this["TextPatternSearchIncludeinput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextPatternSearchIncludeDo {
            get {
                return ((bool)(this["TextPatternSearchIncludeDo"]));
            }
            set {
                this["TextPatternSearchIncludeDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextPatternSearchIncludeQuestions {
            get {
                return ((bool)(this["TextPatternSearchIncludeQuestions"]));
            }
            set {
                this["TextPatternSearchIncludeQuestions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextPatternSearchIncludeCondition {
            get {
                return ((bool)(this["TextPatternSearchIncludeCondition"]));
            }
            set {
                this["TextPatternSearchIncludeCondition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int MinReservedBlockedProcessors {
            get {
                return ((int)(this["MinReservedBlockedProcessors"]));
            }
            set {
                this["MinReservedBlockedProcessors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NonManaged")]
        public global::JaStDev.HAB.CharacterEngine.SpeechEngineMode SpeechEngineMode {
            get {
                return ((global::JaStDev.HAB.CharacterEngine.SpeechEngineMode)(this["SpeechEngineMode"]));
            }
            set {
                this["SpeechEngineMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomSpellingDictsPath {
            get {
                return ((string)(this["CustomSpellingDictsPath"]));
            }
            set {
                this["CustomSpellingDictsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp.bragisoft.com/")]
        public string OnlineInstallationPath {
            get {
                return ((string)(this["OnlineInstallationPath"]));
            }
            set {
                this["OnlineInstallationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedTopicEditor {
            get {
                return ((bool)(this["ToolbarExpandedTopicEditor"]));
            }
            set {
                this["ToolbarExpandedTopicEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextPatternIsAddMode {
            get {
                return ((bool)(this["TextPatternIsAddMode"]));
            }
            set {
                this["TextPatternIsAddMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public global::JaStDev.HAB.Designer.DataToSearch ThesSearchMapCriterium {
            get {
                return ((global::JaStDev.HAB.Designer.DataToSearch)(this["ThesSearchMapCriterium"]));
            }
            set {
                this["ThesSearchMapCriterium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ThesSearchNeedsExactMatch {
            get {
                return ((bool)(this["ThesSearchNeedsExactMatch"]));
            }
            set {
                this["ThesSearchNeedsExactMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ThesSearchAllRelationships {
            get {
                return ((bool)(this["ThesSearchAllRelationships"]));
            }
            set {
                this["ThesSearchAllRelationships"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastCustomDLL {
            get {
                return ((string)(this["LastCustomDLL"]));
            }
            set {
                this["LastCustomDLL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastCustomSource {
            get {
                return ((string)(this["LastCustomSource"]));
            }
            set {
                this["LastCustomSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSelectedEntryPoint {
            get {
                return ((int)(this["LastSelectedEntryPoint"]));
            }
            set {
                this["LastSelectedEntryPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastCustomDestination {
            get {
                return ((string)(this["LastCustomDestination"]));
            }
            set {
                this["LastCustomDestination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolbarExpandedQueryEditor {
            get {
                return ((bool)(this["ToolbarExpandedQueryEditor"]));
            }
            set {
                this["ToolbarExpandedQueryEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double QueryExtraFilesHeight {
            get {
                return ((double)(this["QueryExtraFilesHeight"]));
            }
            set {
                this["QueryExtraFilesHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double QueryExtraFilesWidth {
            get {
                return ((double)(this["QueryExtraFilesWidth"]));
            }
            set {
                this["QueryExtraFilesWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TabSize {
            get {
                return ((int)(this["TabSize"]));
            }
            set {
                this["TabSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double QueryExtraDataHeight {
            get {
                return ((double)(this["QueryExtraDataHeight"]));
            }
            set {
                this["QueryExtraDataHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double QueryExtraDataWidth {
            get {
                return ((double)(this["QueryExtraDataWidth"]));
            }
            set {
                this["QueryExtraDataWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double QueryRTExtraDataHeight {
            get {
                return ((double)(this["QueryRTExtraDataHeight"]));
            }
            set {
                this["QueryRTExtraDataHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double QueryRTExtraDataWidth {
            get {
                return ((double)(this["QueryRTExtraDataWidth"]));
            }
            set {
                this["QueryRTExtraDataWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResponseForDefaultStyleAsPattern {
            get {
                return ((bool)(this["ResponseForDefaultStyleAsPattern"]));
            }
            set {
                this["ResponseForDefaultStyleAsPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextPatternSearchIncludeTopicFilters {
            get {
                return ((bool)(this["TextPatternSearchIncludeTopicFilters"]));
            }
            set {
                this["TextPatternSearchIncludeTopicFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Warning")]
        public global::JaStDev.HAB.LogMethod DuplicatePatternLogMethod {
            get {
                return ((global::JaStDev.HAB.LogMethod)(this["DuplicatePatternLogMethod"]));
            }
            set {
                this["DuplicatePatternLogMethod"] = value;
            }
        }
    }
}
